apiVersion: v1
kind: BuildConfig
metadata:
  name: yogendrasri.test-node
  labels:
    app: test-node
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: https://github.com/yogendrasri/test-node.git
      ref: main
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-yks
        - name: BRANCH
          value: main
